name: Branch

on: 
  push:
    branches-ignore: 
      - master

jobs:

  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: ./dock.py rebuild

  BranchProcess:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Stop the container
      run: ./dock.py stop

    - name: Remove the container
      run: ./dock.py delete

    - name: Startup the test container
      run: ./dock.py start

  WhatsMyIP:
    runs-on: self-hosted
    steps:
    - name: Digit
      run: dig TXT +short o-o.myaddr.l.google.com @ns1.google.com
