name: Branch

on: 
  push:
    branches-ignore: 
      - master

jobs:

  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: docker build --no-cache -tag devnet-create-2020:branchtest .

  BranchProcess:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Stop the container
      run: docker stop devnet_create_2020:branchtest

    - name: Remove the container
      run: docker rm devnet_create_2020:branchtest

    - name: Startup the test container
      run: docker run --name devnet_create_2020 -p 8080:5000 -d devnet-create-2020:branchtest

  WhatsMyIP:
    runs-on: self-hosted
    steps:
    - name: Digit
      run: dig TXT +short o-o.myaddr.l.google.com @ns1.google.com
