name: Branch

on: 
  push:
    branches-ignore: 
      - master

jobs:

  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: docker build . --no-cache --file Dockerfile --tag ignw/devnet_create_2020:branchtest

  BranchProcess:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Startup the test container
      run: docker run --rm --name devnet_branch -dp 8080:5000 ignw/devnet_create_2020:branchtest

  WhatsMyIP:
    runs-on: self-hosted
    steps:
    - name: Digit
      run: dig TXT +short o-o.myaddr.l.google.com @ns1.google.com
