name: Production

on: 
  push:
    branches:
      - master

jobs:

  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: docker build . --file Dockerfile --no-cache --tag devnet-create-2020:production

  ProductionProcess:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Stop the container
      run: docker stop devnet_create_2020:production

    - name: Remove the container
      run: docker rm devnet_create_2020:production

    - name: Startup the test container
      run: docker run --name devnet_create_2020 -p 80:5000 -d devnet-create-2020:production

  WhatsMyIP:
    runs-on: self-hosted
    steps:
    - name: Digit
      run: dig TXT +short o-o.myaddr.l.google.com @ns1.google.com


  WhatsMyIP:
    runs-on: self-hosted
    steps:
    - name: Digit
      run: dig TXT +short o-o.myaddr.l.google.com @ns1.google.com
